//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillPda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICS_Item_Unit_Details
    {
        public long Unit_Entry_Id { get; set; }
        public long Prod_Cd { get; set; }
        public short Alt_Unit_Cd { get; set; }
        public short Base_Unit_Cd { get; set; }
        public decimal Base_Qty { get; set; }
        public decimal Alt_Qty { get; set; }
        public Nullable<short> Line_No { get; set; }
        public bool Protected { get; set; }
        public short User_Cd { get; set; }
        public System.DateTime User_Date_Time { get; set; }
        public byte[] Time_Stamp { get; set; }
        public System.Guid row_id { get; set; }
        public decimal Sales_Rate { get; set; }
    
        public virtual ICS_Item ICS_Item { get; set; }
    }
}
