//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillPda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICS_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ICS_Item()
        {
            this.ICS_Transaction_Details = new HashSet<ICS_Transaction_Details>();
            this.ICS_Item_Unit_Details = new HashSet<ICS_Item_Unit_Details>();
        }
    
        public long Prod_Cd { get; set; }
        public int Group_Cd { get; set; }
        public int Cat_Cd { get; set; }
        public short Base_Unit_Cd { get; set; }
        public byte Item_Type_Cd { get; set; }
        public string Part_No { get; set; }
        public string L_Prod_Name { get; set; }
        public string A_Prod_Name { get; set; }
        public string Prod_Desc { get; set; }
        public decimal Cost { get; set; }
        public byte Costing_Method { get; set; }
        public string Cash_Sale_Cd { get; set; }
        public string Credit_Sale_Cd { get; set; }
        public string Inventory_Cd { get; set; }
        public string Cost_Of_Sale_Cd { get; set; }
        public decimal Current_Qty { get; set; }
        public decimal Stock_In_Hand { get; set; }
        public decimal Stock_Allocated { get; set; }
        public decimal Stock_Reserved { get; set; }
        public decimal Stock_Booked { get; set; }
        public Nullable<decimal> Stock_Available { get; set; }
        public decimal Stock_In_Transit { get; set; }
        public decimal Stock_On_Order { get; set; }
        public decimal Stock_Return_In_Transit { get; set; }
        public decimal MTD_Usage { get; set; }
        public decimal YTD_Usage { get; set; }
        public decimal Avg_Monthly_Usage { get; set; }
        public decimal Tot_Qty_In { get; set; }
        public decimal Tot_Qty_Out { get; set; }
        public Nullable<int> Supplier_Ldgr_Cd { get; set; }
        public string Supplier_Part_No { get; set; }
        public string ABC_Category { get; set; }
        public string Picture { get; set; }
        public Nullable<decimal> Maximum_Level { get; set; }
        public Nullable<decimal> Minimum_Level { get; set; }
        public Nullable<decimal> Reorder_Level { get; set; }
        public Nullable<decimal> Maximum_Reorder_Qty { get; set; }
        public Nullable<decimal> Minimum_Reorder_Qty { get; set; }
        public Nullable<decimal> Last_Purchased_Qty { get; set; }
        public Nullable<decimal> Last_Sold_Qty { get; set; }
        public string Last_Supplier_Cd { get; set; }
        public string Last_Customer_Cd { get; set; }
        public Nullable<System.DateTime> Last_Purchased_Date { get; set; }
        public Nullable<System.DateTime> Last_Sold_Date { get; set; }
        public Nullable<short> Last_Purchased_Unit_Cd { get; set; }
        public Nullable<short> Last_Sold_Unit_Cd { get; set; }
        public Nullable<decimal> Purchase_Rate { get; set; }
        public Nullable<decimal> Purchase_Rate_1 { get; set; }
        public Nullable<decimal> Purchase_Rate_2 { get; set; }
        public Nullable<decimal> Purchase_Rate_3 { get; set; }
        public Nullable<decimal> Purchase_Rate_4 { get; set; }
        public Nullable<decimal> Purchase_Rate_5 { get; set; }
        public Nullable<decimal> Sales_Rate { get; set; }
        public Nullable<decimal> Sale_Rate1 { get; set; }
        public Nullable<decimal> Sale_Rate2 { get; set; }
        public Nullable<decimal> Sale_Rate3 { get; set; }
        public Nullable<decimal> Sale_Rate4 { get; set; }
        public Nullable<decimal> Sale_Rate5 { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public Nullable<decimal> Warranty_Period_In_Days { get; set; }
        public bool Serialized { get; set; }
        public bool Discontinued { get; set; }
        public bool Promotional_Item { get; set; }
        public Nullable<bool> Print_Components_On_Voucher { get; set; }
        public Nullable<decimal> Commision_In_Percent_On_Sales { get; set; }
        public Nullable<decimal> Commision_In_Percent_On_Purchase { get; set; }
        public string Comments { get; set; }
        public bool Protected { get; set; }
        public short User_Cd { get; set; }
        public System.DateTime User_Date_Time { get; set; }
        public byte[] Time_Stamp { get; set; }
        public System.Guid row_id { get; set; }
        public decimal Stock_On_Order_Of_Sales { get; set; }
        public byte[] Picture_Object { get; set; }
        public Nullable<short> Updated_By_User_Cd { get; set; }
        public Nullable<System.DateTime> Updated_Date_Time { get; set; }
        public string Offline_Data_Updated_Locat_Cd { get; set; }
        public string Bin_Location { get; set; }
        public decimal Weight { get; set; }
        public string Flex1_VSSV_Code { get; set; }
        public string Flex2_VSSV_Code { get; set; }
        public string Flex3_VSSV_Code { get; set; }
        public string Flex4_VSSV_Code { get; set; }
        public string Flex5_VSSV_Code { get; set; }
        public string Flex6_VSSV_Code { get; set; }
        public string Flex7_VSSV_Code { get; set; }
        public string Flex8_VSSV_Code { get; set; }
        public string Flex9_VSSV_Code { get; set; }
        public string Flex10_VSSV_Code { get; set; }
        public string Flex11_VSSV_Code { get; set; }
        public string Flex12_VSSV_Code { get; set; }
        public string Flex13_VSSV_Code { get; set; }
        public string Flex14_VSSV_Code { get; set; }
        public short Report_Unit_Cd { get; set; }
        public string package { get; set; }
        public string ExpDate { get; set; }
        public string MadeIn { get; set; }
        public string PackDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICS_Transaction_Details> ICS_Transaction_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICS_Item_Unit_Details> ICS_Item_Unit_Details { get; set; }
        public virtual ICS_Item_Group ICS_Item_Group { get; set; }
    }
}
