//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillPda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imill_BranchOrderItem
    {
        public long OrderItemId { get; set; }
        public long Locat_cd { get; set; }
        public long Prod_Cd { get; set; }
        public bool Show { get; set; }
        public long SortOrder { get; set; }
        public string QtyRange { get; set; }
    }
}
