//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillPda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenTransaction
    {
        public int Oid { get; set; }
        public long EntryId { get; set; }
        public long Prod_Cd { get; set; }
        public string PartNumber { get; set; }
        public long Locat_Cd { get; set; }
        public decimal RequiredQty { get; set; }
        public decimal ActualQty { get; set; }
        public Nullable<decimal> RequestedQty { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsNewlyAdded { get; set; }
        public bool IsReqQtyChanged { get; set; }
    }
}
