//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillPda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Oid { get; set; }
        public System.DateTime TransDate { get; set; }
        public long Locat_Cd { get; set; }
        public long EntryId { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public bool IsCompleted { get; set; }
        public int TransactionId { get; set; }
        public string Remarks { get; set; }
    }
}
