//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillPda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int Oid { get; set; }
        public long Prod_Cd { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public decimal Qty { get; set; }
        public decimal ActualQty { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public long Entry_Id { get; set; }
        public int TransactionOid { get; set; }
        public decimal DeliveredQty { get; set; }
        public decimal RemainingQty { get; set; }
        public bool IsDelivered { get; set; }
        public long Line_No { get; set; }
    }
}
