//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }
    
        public int Oid { get; set; }
        public System.DateTime TransDate { get; set; }
        public long TransactionNumber { get; set; }
        public int ItemsCount { get; set; }
        public bool IsEmailSent { get; set; }
        public bool IsPrinted { get; set; }
        public Nullable<System.DateTime> EmailSentOn { get; set; }
        public Nullable<System.DateTime> PrintedOn { get; set; }
        public bool IsDeleted { get; set; }
        public int RequestedBy { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string TransNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
    }
}
