//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int Oid { get; set; }
        public System.DateTime TransDate { get; set; }
        public long ItemOid { get; set; }
        public string ItemNameEn { get; set; }
        public string ItemNameAr { get; set; }
        public long UnitOid { get; set; }
        public string UnitNameEn { get; set; }
        public string UnitNameAr { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public long TransactionNumber { get; set; }
        public int TransactionId { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
