//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Oid { get; set; }
        public string Id { get; set; }
        public string UserName { get; set; }
        public string FullnameEn { get; set; }
        public string FullnameAr { get; set; }
        public bool IsDeleted { get; set; }
        public string Email { get; set; }
        public bool IsRegForEmail { get; set; }
        public bool IsActiveDropDown { get; set; }
    }
}
