//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryCount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int Oid { get; set; }
        public long TransactionId { get; set; }
        public System.DateTime TransDate { get; set; }
        public string PartNumber { get; set; }
        public int Weight { get; set; }
        public long ItemOid { get; set; }
        public string ItemNameEn { get; set; }
        public string ItemNameAr { get; set; }
    }
}
