//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosDelivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickupDelivery
    {
        public int Oid { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<int> TimeSlot_Oid { get; set; }
    
        public virtual TimeSlot TimeSlot { get; set; }
    }
}
