//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosDelivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosOrderDetail
    {
        public int Oid { get; set; }
        public string ItemNameEn { get; set; }
        public string ItemNameAr { get; set; }
        public string Unit { get; set; }
        public int Qty { get; set; }
        public decimal Amount { get; set; }
        public string OrderOid { get; set; }
    }
}
