//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosDelivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAttributeValue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductAttributeValue()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.ShoppingCarts = new HashSet<ShoppingCart>();
        }
    
        public int ProductAttributeValueId { get; set; }
        public string ProductAttributeValueName { get; set; }
        public string ProductAttributeValueNameAr { get; set; }
        public decimal SalesPrice { get; set; }
        public int StockQuantity { get; set; }
        public int MaxOrder { get; set; }
        public Nullable<int> LowStockQuantity { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> Product_ProductAttribute_Mapping_ProductAttributeMappingId { get; set; }
        public string Barcode { get; set; }
        public int MinOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual Product_ProductAttribute_Mapping Product_ProductAttribute_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
    }
}
