//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosDelivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public int OrderLimitCount { get; set; }
        public string SiteMessageEn { get; set; }
        public string SiteMessageAr { get; set; }
        public int CustomLimitCount { get; set; }
        public bool IsCustomActivated { get; set; }
        public System.DateTime CustomLimitDate { get; set; }
        public bool IsCartActive { get; set; }
        public string CartDisableMessageEn { get; set; }
        public string CartDisableMessageAr { get; set; }
        public int PickupLimitCount { get; set; }
    }
}
