//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosDelivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int ShipmentId { get; set; }
        public int ShippingStatus { get; set; }
        public string TrackingNumber { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string AdminComment { get; set; }
        public Nullable<int> Order_OrderId { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
