//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosDelivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentSetting
    {
        public int ShipmentSettingsId { get; set; }
        public decimal StandardShippingCharges { get; set; }
        public decimal FreeShippingAmountLimit { get; set; }
    }
}
