//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosDelivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int ShoppingCartId { get; set; }
        public int ShoppingCartType { get; set; }
        public int Quantity { get; set; }
        public decimal TotalCost { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> Customer_CustomerGuid { get; set; }
        public Nullable<int> Products_ProductID { get; set; }
        public Nullable<int> ProductAttributeValue_ProductAttributeValueId { get; set; }
        public decimal ShippingCost { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ProductAttributeValue ProductAttributeValue { get; set; }
        public virtual Product Product { get; set; }
    }
}
