'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ICS_Item
    Public Property Prod_Cd As Long
    Public Property Group_Cd As Integer
    Public Property Cat_Cd As Integer
    Public Property Base_Unit_Cd As Short
    Public Property Item_Type_Cd As Byte
    Public Property Part_No As String
    Public Property L_Prod_Name As String
    Public Property A_Prod_Name As String
    Public Property Prod_Desc As String
    Public Property Cost As Decimal
    Public Property Costing_Method As Byte
    Public Property Cash_Sale_Cd As String
    Public Property Credit_Sale_Cd As String
    Public Property Inventory_Cd As String
    Public Property Cost_Of_Sale_Cd As String
    Public Property Current_Qty As Decimal
    Public Property Stock_In_Hand As Decimal
    Public Property Stock_Allocated As Decimal
    Public Property Stock_Reserved As Decimal
    Public Property Stock_Booked As Decimal
    Public Property Stock_Available As Nullable(Of Decimal)
    Public Property Stock_In_Transit As Decimal
    Public Property Stock_On_Order As Decimal
    Public Property Stock_Return_In_Transit As Decimal
    Public Property MTD_Usage As Decimal
    Public Property YTD_Usage As Decimal
    Public Property Avg_Monthly_Usage As Decimal
    Public Property Tot_Qty_In As Decimal
    Public Property Tot_Qty_Out As Decimal
    Public Property Supplier_Ldgr_Cd As Nullable(Of Integer)
    Public Property Supplier_Part_No As String
    Public Property ABC_Category As String
    Public Property Picture As String
    Public Property Maximum_Level As Nullable(Of Decimal)
    Public Property Minimum_Level As Nullable(Of Decimal)
    Public Property Reorder_Level As Nullable(Of Decimal)
    Public Property Maximum_Reorder_Qty As Nullable(Of Decimal)
    Public Property Minimum_Reorder_Qty As Nullable(Of Decimal)
    Public Property Last_Purchased_Qty As Nullable(Of Decimal)
    Public Property Last_Sold_Qty As Nullable(Of Decimal)
    Public Property Last_Supplier_Cd As String
    Public Property Last_Customer_Cd As String
    Public Property Last_Purchased_Date As Nullable(Of Date)
    Public Property Last_Sold_Date As Nullable(Of Date)
    Public Property Last_Purchased_Unit_Cd As Nullable(Of Short)
    Public Property Last_Sold_Unit_Cd As Nullable(Of Short)
    Public Property Purchase_Rate As Nullable(Of Decimal)
    Public Property Purchase_Rate_1 As Nullable(Of Decimal)
    Public Property Purchase_Rate_2 As Nullable(Of Decimal)
    Public Property Purchase_Rate_3 As Nullable(Of Decimal)
    Public Property Purchase_Rate_4 As Nullable(Of Decimal)
    Public Property Purchase_Rate_5 As Nullable(Of Decimal)
    Public Property Sales_Rate As Nullable(Of Decimal)
    Public Property Sale_Rate1 As Nullable(Of Decimal)
    Public Property Sale_Rate2 As Nullable(Of Decimal)
    Public Property Sale_Rate3 As Nullable(Of Decimal)
    Public Property Sale_Rate4 As Nullable(Of Decimal)
    Public Property Sale_Rate5 As Nullable(Of Decimal)
    Public Property Expiry_Date As Nullable(Of Date)
    Public Property Warranty_Period_In_Days As Nullable(Of Decimal)
    Public Property Serialized As Boolean
    Public Property Discontinued As Boolean
    Public Property Promotional_Item As Boolean
    Public Property Print_Components_On_Voucher As Nullable(Of Boolean)
    Public Property Commision_In_Percent_On_Sales As Nullable(Of Decimal)
    Public Property Commision_In_Percent_On_Purchase As Nullable(Of Decimal)
    Public Property Comments As String
    Public Property [Protected] As Boolean
    Public Property User_Cd As Short
    Public Property User_Date_Time As Date
    Public Property Time_Stamp As Byte()
    Public Property row_id As System.Guid
    Public Property Stock_On_Order_Of_Sales As Decimal
    Public Property Picture_Object As Byte()
    Public Property Updated_By_User_Cd As Nullable(Of Short)
    Public Property Updated_Date_Time As Nullable(Of Date)
    Public Property Offline_Data_Updated_Locat_Cd As String
    Public Property Bin_Location As String
    Public Property Weight As Decimal
    Public Property Flex1_VSSV_Code As String
    Public Property Flex2_VSSV_Code As String
    Public Property Flex3_VSSV_Code As String
    Public Property Flex4_VSSV_Code As String
    Public Property Flex5_VSSV_Code As String
    Public Property Flex6_VSSV_Code As String
    Public Property Flex7_VSSV_Code As String
    Public Property Flex8_VSSV_Code As String
    Public Property Flex9_VSSV_Code As String
    Public Property Flex10_VSSV_Code As String
    Public Property Flex11_VSSV_Code As String
    Public Property Flex12_VSSV_Code As String
    Public Property Flex13_VSSV_Code As String
    Public Property Flex14_VSSV_Code As String
    Public Property Report_Unit_Cd As Short
    Public Property package As String
    Public Property ExpDate As String
    Public Property MadeIn As String
    Public Property PackDate As String

    Public Overridable Property ICS_Transaction_Details As ICollection(Of ICS_Transaction_Details) = New HashSet(Of ICS_Transaction_Details)

End Class
