'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ICS_Transaction
    Public Property Entry_Id As Long
    Public Property Voucher_Type As Short
    Public Property Locat_Cd As Short
    Public Property Ldgr_Cd As Nullable(Of Integer)
    Public Property Sman_Cd As Short
    Public Property Cash_Cd As Nullable(Of Integer)
    Public Property Linked_To_Voucher_Type As Nullable(Of Short)
    Public Property Linked_To_Entry_Id As Nullable(Of Long)
    Public Property Batch_Cd As Nullable(Of Long)
    Public Property Exchange_Rate As Decimal
    Public Property Voucher_Date As Date
    Public Property Voucher_No As Long
    Public Property Reference_No As String
    Public Property Is_Cash As Boolean
    Public Property Voucher_Amt_FC As Decimal
    Public Property Voucher_Amt_LC As Nullable(Of Decimal)
    Public Property Discount_Amt_FC As Decimal
    Public Property Discount_Amt_LC As Nullable(Of Decimal)
    Public Property Net_Amt_FC As Nullable(Of Decimal)
    Public Property Net_Amt_LC As Nullable(Of Decimal)
    Public Property Expenses_Amt As Decimal
    Public Property Paid_Amt As Decimal
    Public Property Due_Amt As Decimal
    Public Property Due_Date As Nullable(Of Date)
    Public Property On_Hand_Stock_Affected As Boolean
    Public Property Close_Transaction As Boolean
    Public Property Transaction_Processed As Boolean
    Public Property Transaction_Year_Closed As Boolean
    Public Property Printed_Counter As Integer
    Public Property Processed As Boolean
    Public Property Reversed As Boolean
    Public Property Reconciled As Boolean
    Public Property Reconciled_Date As Nullable(Of Date)
    Public Property Comments As String
    Public Property Posted_Invnt As Boolean
    Public Property Status As Byte
    Public Property Posted_GL_Party As Boolean
    Public Property Posted_GL_Expense As Boolean
    Public Property Posted_GL_Inventory As Boolean
    Public Property Posted_GL As Boolean
    Public Property User_Cd As Short
    Public Property User_Date_Time As Date
    Public Property Time_Stamp As Byte()
    Public Property row_id As System.Guid
    Public Property Anly_Code_1 As String
    Public Property Anly_Code_2 As String
    Public Property Anly_Head_No_1 As Nullable(Of Byte)
    Public Property Anly_Head_No_2 As Nullable(Of Byte)
    Public Property Curr_Cd As Nullable(Of Short)
    Public Property Revision_No As Integer
    Public Property Cash_Amt_FC As Decimal
    Public Property Credit_Card_Ldgr_Cd As Nullable(Of Integer)
    Public Property Credit_Card_Amt_FC As Decimal
    Public Property Change_Amt_FC As Decimal
    Public Property Amount_Received As Decimal
    Public Property POS_Counter_Cd As Nullable(Of Integer)
    Public Property Expenses_Ldgr_Cd As Nullable(Of Integer)
    Public Property Consignment_Cd As Nullable(Of Integer)
    Public Property Discount_Percent As Decimal
    Public Property Ldgr_Name As String
    Public Property Project_Cd As Nullable(Of Long)
    Public Property Acty_Cd As Nullable(Of Long)
    Public Property From_Date As Nullable(Of Date)
    Public Property To_Date As Nullable(Of Date)
    Public Property Delevery_Date As Nullable(Of Date)
    Public Property Return_Date As Nullable(Of Date)
    Public Property Discount2_percent As Nullable(Of Decimal)
    Public Property Discount2_Amt As Nullable(Of Decimal)
    Public Property Credit_voucher_no As String
    Public Property Credit_voucher_Amt_FC As Nullable(Of Decimal)
    Public Property Credit_Voucher_Ldgr_Cd As Nullable(Of Integer)
    Public Property Credit_Card_Type As String
    Public Property Additional_Field_1 As String
    Public Property Additional_Field_2 As String
    Public Property Additional_Field_3 As String
    Public Property Additional_Field_4 As String
    Public Property Additional_Field_5 As String
    Public Property Additional_Field_6 As String
    Public Property Additional_Field_7 As String

    Public Overridable Property ICS_Transaction_Details As ICollection(Of ICS_Transaction_Details) = New HashSet(Of ICS_Transaction_Details)
    Public Overridable Property ICS_Transaction1 As ICollection(Of ICS_Transaction) = New HashSet(Of ICS_Transaction)
    Public Overridable Property ICS_Transaction2 As ICS_Transaction

End Class
