'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ICS_Transaction_Details
    Public Property Line_No As Long
    Public Property Entry_Id As Long
    Public Property Add_Locat_Cd As Nullable(Of Short)
    Public Property Less_Locat_Cd As Nullable(Of Short)
    Public Property Prod_Cd As Long
    Public Property Project_Cd As Nullable(Of Long)
    Public Property Unit_Entry_ID As Long
    Public Property Linked_Line_No As Nullable(Of Long)
    Public Property Exchange_Rate As Decimal
    Public Property Prod_Name As String
    Public Property Reference_No As String
    Public Property Qty As Decimal
    Public Property Base_Qty As Decimal
    Public Property Processed_Qty As Decimal
    Public Property Balance_Qty As Nullable(Of Decimal)
    Public Property FC_Rate As Decimal
    Public Property FC_Prod_Dis As Decimal
    Public Property FC_Amount As Decimal
    Public Property LC_Rate As Nullable(Of Decimal)
    Public Property LC_Prod_Dis As Nullable(Of Decimal)
    Public Property LC_Amount As Nullable(Of Decimal)
    Public Property Prod_Exp_Amt As Decimal
    Public Property Promo_Type As String
    Public Property Item_Cost As Decimal
    Public Property Dis_In_Percent As Boolean
    Public Property Linked As Boolean
    Public Property Show As Boolean
    Public Property GL_Post_Sequence_Counter As Long
    Public Property Status As Byte
    Public Property User_Date_Time As Date
    Public Property row_id As System.Guid
    Public Property Non_Stock_Manual_Cost As Decimal
    Public Property Item_Type_Cd As Byte
    Public Property Is_Dented As Boolean
    Public Property Rate_UOM_Symbol As String
    Public Property Weight As Decimal
    Public Property Linked_To_Voucher_Type As Nullable(Of Short)
    Public Property Linked_To_Line_Id As Nullable(Of Long)
    Public Property Processed_SQ_Base_Qty As Decimal
    Public Property Processed_PO_Base_Qty As Decimal
    Public Property Processed_GRN_Base_Qty As Decimal
    Public Property Processed_CQ_Base_Qty As Decimal
    Public Property Processed_SO_Base_Qty As Decimal
    Public Property Processed_INV_Base_Qty As Decimal
    Public Property Processed_CSR_Base_Qty As Decimal
    Public Property Processed_SR_Base_Qty As Decimal
    Public Property Processed_STS_Base_Qty As Decimal
    Public Property Processed_ESTK_Base_Qty As Decimal
    Public Property Processed_SSTK_Base_Qty As Decimal
    Public Property Processed_Others_Base_Qty As Decimal
    Public Property Balance_Qty_1 As Nullable(Of Decimal)
    Public Property Pre_Text As String
    Public Property Post_Text As String
    Public Property Expiry_Date As Nullable(Of Date)
    Public Property Fc_Prod_Dis_Per As Decimal
    Public Property Flex1 As String
    Public Property Commission_Amt As Decimal
    Public Property master_discount As Decimal
    Public Property Print_sr_no As Nullable(Of Integer)
    Public Property Pack_Qty As Nullable(Of Decimal)
    Public Property Loose_Qty As Nullable(Of Decimal)
    Public Property Barcode As String
    Public Property Acty_Task_Cd As Nullable(Of Long)
    Public Property Acty_Cd As Nullable(Of Long)
    Public Property Package As Nullable(Of Decimal)
    Public Property batch_cd As String
    Public Property production_status As Nullable(Of Boolean)
    Public Property Additional_Field_1 As String
    Public Property Additional_Field_2 As String
    Public Property Additional_Field_3 As String
    Public Property Additional_Field_4 As String
    Public Property Additional_Field_5 As String
    Public Property Additional_Field_6 As String
    Public Property Additional_Field_7 As String

    Public Overridable Property ICS_Item As ICS_Item
    Public Overridable Property ICS_Transaction As ICS_Transaction
    Public Overridable Property ICS_Transaction_Details1 As ICollection(Of ICS_Transaction_Details) = New HashSet(Of ICS_Transaction_Details)
    Public Overridable Property ICS_Transaction_Details2 As ICS_Transaction_Details

End Class
