'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class IMILLEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=IMILLEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ICS_Item() As DbSet(Of ICS_Item)
    Public Overridable Property ICS_Transaction() As DbSet(Of ICS_Transaction)
    Public Overridable Property ICS_Transaction_Details() As DbSet(Of ICS_Transaction_Details)

End Class
