//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntlmillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICS_Transaction_Types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ICS_Transaction_Types()
        {
            this.ICS_Transaction = new HashSet<ICS_Transaction>();
            this.ICS_Transaction1 = new HashSet<ICS_Transaction>();
            this.ICS_Transaction_Types11 = new HashSet<ICS_Transaction_Types>();
            this.ICS_Transaction_Types12 = new HashSet<ICS_Transaction_Types>();
        }
    
        public short Voucher_Type { get; set; }
        public short Parent_Type { get; set; }
        public short Module_Id { get; set; }
        public short Feature_Id { get; set; }
        public long Find_Id { get; set; }
        public Nullable<short> Linked_Assembly_Group_Adjust_Voucher_Type { get; set; }
        public string L_Voucher_Name { get; set; }
        public string A_Voucher_Name { get; set; }
        public string L_Short_Name { get; set; }
        public string A_Short_Name { get; set; }
        public string Add_Or_Less { get; set; }
        public bool Locat_To_Locat { get; set; }
        public bool Generate_On_Multiple_Location { get; set; }
        public string Master_Table_Name { get; set; }
        public string Details_Table_Name { get; set; }
        public string Linked_ICS_Master_Table_Name { get; set; }
        public string Linked_ICS_Details_Table_Name { get; set; }
        public string Linked_ICS_Parent_Master_Table_Name { get; set; }
        public string Linked_ICS_Parent_Details_Table_Name { get; set; }
        public Nullable<short> Linked_Parent_ICS_Voucher_Type_Cd { get; set; }
        public Nullable<short> Linked_Child_ICS_Voucher_Type_Cd { get; set; }
        public Nullable<short> Linked_GL_Voucher_Type_Cd { get; set; }
        public short Linked_GL_Receipt_Voucher_Type_Cd { get; set; }
        public short Linked_GL_Payment_Voucher_Type_Cd { get; set; }
        public short Linked_GL_Journal_Voucher_Type_Cd { get; set; }
        public bool Auto_Generate_Linked_Voucher { get; set; }
        public bool Auto_Generate_Voucher_No { get; set; }
        public bool Auto_Post_ICS { get; set; }
        public bool Auto_Post_GL_Party { get; set; }
        public bool Auto_Post_Status { get; set; }
        public bool Auto_Post_GL_Expense { get; set; }
        public bool Auto_Post_GL_Inventory { get; set; }
        public bool Auto_Post_GL { get; set; }
        public bool Batch_Post_ICS { get; set; }
        public bool Batch_Post_GL_Party { get; set; }
        public bool Batch_Post_Status { get; set; }
        public bool Batch_Post_GL_Expense { get; set; }
        public bool Batch_Post_GL_Inventory { get; set; }
        public bool Batch_Post_GL { get; set; }
        public bool Affect_GLS { get; set; }
        public bool Affect_ICS { get; set; }
        public bool Affect_Cost { get; set; }
        public bool Affect_Opening_Value { get; set; }
        public bool Affect_On_Hand_Stock { get; set; }
        public bool Affect_Allocated_Stock { get; set; }
        public bool Affect_In_Transit_Stock { get; set; }
        public bool Affect_On_Order_Stock { get; set; }
        public bool Affect_Reserved_Stock { get; set; }
        public bool Affect_Advanced_Booked_Stock { get; set; }
        public bool Affect_Stock_Return_In_Transit { get; set; }
        public bool Affect_MTD_Usage { get; set; }
        public bool Affect_YTD_Usage { get; set; }
        public bool Affect_On_Order_Stock_Of_Sales { get; set; }
        public bool Show_Message_When_Negative_Stock { get; set; }
        public bool Show_Location_On_Header { get; set; }
        public bool Show_Ledger_On_Header { get; set; }
        public bool Show_Cash_Credit_On_Header { get; set; }
        public bool Show_Remarks_On_Header { get; set; }
        public bool Show_Import_Linked_Voucher_On_Header { get; set; }
        public bool Show_Line_No_In_Details { get; set; }
        public bool Show_Part_No_In_Details { get; set; }
        public bool Show_Product_Name_In_Details { get; set; }
        public bool Show_Unit_In_Details { get; set; }
        public bool Show_Promo_In_Details { get; set; }
        public bool Show_Qty_In_Details { get; set; }
        public bool Show_Remaining_Qty_In_Details { get; set; }
        public bool Show_Rate_In_Details { get; set; }
        public bool Show_Product_Discount_In_Details { get; set; }
        public bool Show_Amount_In_Details { get; set; }
        public bool Show_Location_In_Details { get; set; }
        public bool Show_Remarks_In_Details { get; set; }
        public bool Show_Serial_In_Details { get; set; }
        public bool Show_Barcode_In_Details { get; set; }
        public bool Show_Project_In_Details { get; set; }
        public bool Show_Expenses { get; set; }
        public bool Show_Exchange_Rate { get; set; }
        public bool Show_Salesman { get; set; }
        public bool Show_Percent_Discount { get; set; }
        public bool Show_Net_Amount { get; set; }
        public bool Show_Product_Base_Unit_In_List { get; set; }
        public bool Show_Product_Group_In_List { get; set; }
        public bool Show_Product_Category_In_List { get; set; }
        public bool Show_Purchase_Price_In_List { get; set; }
        public bool Show_Sales_Price_In_List { get; set; }
        public bool Show_Base_Unit_In_Status { get; set; }
        public bool Show_Stock_In_Hand_In_Status { get; set; }
        public bool Show_Stock_Allocated_In_Status { get; set; }
        public bool Show_Stock_Available_In_Status { get; set; }
        public bool Show_In_Transit_Stock_In_Status { get; set; }
        public bool Show_On_Order_Stock_In_Status { get; set; }
        public bool Show_Advanced_Booked_Stock_In_Status { get; set; }
        public bool Show_Stock_Return_In_Transit_In_Status { get; set; }
        public bool Show_MTD_Usage_In_Status { get; set; }
        public bool Show_YTD_Usage_In_Status { get; set; }
        public bool Show_On_Order_Stock_Of_Sales_In_Status { get; set; }
        public bool Show_Additional_Voucher_Details { get; set; }
        public bool Show_in_Menu { get; set; }
        public bool Show_Details_In_Product_Query { get; set; }
        public bool Show_Print_Preview_First { get; set; }
        public bool Show_Page_Setup_First { get; set; }
        public bool Check_Negative_Stock { get; set; }
        public bool Print_After_Save { get; set; }
        public string Print_Voucher_Name { get; set; }
        public string Print_Voucher_Sql { get; set; }
        public bool Close_Preview_Windows_After_Print { get; set; }
        public bool Include_Location_In_Voucher { get; set; }
        public bool Include_Voucher_No_In_Voucher { get; set; }
        public bool Include_Reference_No_In_Voucher { get; set; }
        public bool Allow_Online_GL_Post { get; set; }
        public bool Allow_Excess_Qty_When_Linked { get; set; }
        public bool Allow_Product_Name_Alteration { get; set; }
        public bool Allow_Add_Serial_No_When_Not_Exists { get; set; }
        public bool Allow_Add_New_Voucher { get; set; }
        public bool Allow_Update_Voucher { get; set; }
        public bool Enable_Rate_When_Linked { get; set; }
        public bool Enable_Discount_When_Linked { get; set; }
        public bool Enable_Amount_When_Linked { get; set; }
        public bool Enable_Cash_Credit_On_Header_When_Linked { get; set; }
        public bool Enable_Percent_Discount_On_Header_When_Linked { get; set; }
        public string Additional_Ledger_Find_Where_Clause { get; set; }
        public string Additional_Cash_Find_Where_Clause { get; set; }
        public long Voucher_Grid_Back_Color { get; set; }
        public string L_Party_Name_Caption { get; set; }
        public string A_Party_Name_Caption { get; set; }
        public bool Restore_Last_Tran_Setting { get; set; }
        public string Last_Tran_Locat_No { get; set; }
        public Nullable<bool> Last_Tran_Cash_Type { get; set; }
        public string Last_Tran_Cash_No { get; set; }
        public string Last_Tran_Sman_No { get; set; }
        public bool Show { get; set; }
        public bool Protected { get; set; }
        public string Comments { get; set; }
        public Nullable<short> User_Cd { get; set; }
        public System.Guid row_id { get; set; }
        public bool Begin_With_Line_Seperator { get; set; }
        public bool Show_Product_Dis_Per_In_Details { get; set; }
        public string Last_Tran_Ldgr_No { get; set; }
        public string After_Save_Script { get; set; }
        public bool Setfocus_To_Newline_After_Barcode_Entered { get; set; }
        public bool Setfocus_To_Newline_After_Qty_Entered { get; set; }
        public bool Show_Party_Balance_On_Header { get; set; }
        public bool Display_Voucher_No_After_Save { get; set; }
        public Nullable<int> Adjustment_Cd { get; set; }
        public bool Show_Non_Inventory_In_Details { get; set; }
        public bool Import_Non_Inventory_From_Parent_Voucher { get; set; }
        public bool Show_Amount_Over_Rate { get; set; }
        public bool Show_Dented_Stock_In_Details { get; set; }
        public Nullable<short> Dented_Stock_Generated_Linked_Voucher_Type { get; set; }
        public bool Show_Batch_Cd_On_Header { get; set; }
        public bool Show_Location_Specific_Product { get; set; }
        public bool Use_Crystal_Reports_For_Print { get; set; }
        public Nullable<long> Crystal_Report_Id { get; set; }
        public Nullable<long> Report_Entry_Id_Column { get; set; }
        public bool Use_Report_Additional_Column_Ids { get; set; }
        public string Report_Additional_Column_Ids { get; set; }
        public bool Use_Num_To_Char_Function { get; set; }
        public Nullable<bool> Enable_ICS_Voucher_Final_Payment_Screen { get; set; }
        public bool Import_External_Data { get; set; }
        public bool Setfocus_To_Grid_After_Add_New { get; set; }
        public bool Auto_Post_Stock_Generated_Linked_Voucher_Type { get; set; }
        public bool Show_Default_Location_Salesman { get; set; }
        public bool auto_generate_linked_voucher_all_location { get; set; }
        public byte Rate_Setting_In_Details { get; set; }
        public byte Amount_Setting_In_Details { get; set; }
        public bool Prompt_For_Print_After_Save { get; set; }
        public bool Prompt_Before_Save { get; set; }
        public bool Check_Part_No_Exists { get; set; }
        public bool Check_Prod_Name_Exists { get; set; }
        public bool Show_Due_Date_On_Header { get; set; }
        public bool Preserve_Grid_Value_During_Import { get; set; }
        public bool Show_Weight_In_Details { get; set; }
        public bool Show_Rate_UOM_In_Details { get; set; }
        public bool Enable_Auto_Generate_Linked_Voucher_For_Cash_Transaction { get; set; }
        public int Document_Type { get; set; }
        public int Default_Price_Level_Priority { get; set; }
        public bool Show_Job_Cd_On_Header { get; set; }
        public bool Show_Import_Linked_Voucher_In_Details { get; set; }
        public bool Use_Processed_Qty_Sum_While_Linking { get; set; }
        public bool Bind_To_Parent_Header_Location { get; set; }
        public bool Bind_To_Parent { get; set; }
        public bool Enable_Doc_Presc_In_Additional_Voucher_Details { get; set; }
        public bool Enable_Partial_Receipt { get; set; }
        public bool Enable_ICS_Voucher_Multiline_PreDesc { get; set; }
        public bool Enable_ICS_Voucher_Multiline_PostDesc { get; set; }
        public bool Enable_Revision { get; set; }
        public Nullable<short> Revised_History_Voucher_Type { get; set; }
        public int Reference_No_Generate_Method { get; set; }
        public bool Enable_Additional_Voucher_Details_2 { get; set; }
        public string Reference_No_L_Caption { get; set; }
        public bool Enable_Auto_Fill_Pre_Text_With_Product_Desc { get; set; }
        public bool Export_To_Word { get; set; }
        public bool Allow_Direct_Transaction { get; set; }
        public int Form_Height_Size { get; set; }
        public int Grid_Row_Height_Size { get; set; }
        public bool Show_Supplier_Tab_In_ICS_Voucher { get; set; }
        public bool Show_Expenses_Ldgr_Code_On_Header { get; set; }
        public bool Affect_GL_With_Expenses_Ldgr_Cd { get; set; }
        public string Expenses_Ldgr_Find_Where_Clause { get; set; }
        public bool Show_Consignment_No_On_Header { get; set; }
        public bool Get_Max_New_Voucher_No { get; set; }
        public bool Allow_Zero_Amount_Transaction { get; set; }
        public bool Show_Expiry_In_Details { get; set; }
        public string Product_List_Where_Clause { get; set; }
        public bool Default_Location_Salesman { get; set; }
        public bool Show_In_Periodical_Batch_Post { get; set; }
        public bool Show_Message_On_Items_Below_Reorder_Level { get; set; }
        public bool Show_Message_On_Items_Below_Minimum_Level { get; set; }
        public bool Show_Message_On_Items_Above_Maximum_Level { get; set; }
        public Nullable<int> Default_cash_cd { get; set; }
        public bool generate_receipt_payment_voucher { get; set; }
        public bool Show_Flex1_In_Details { get; set; }
        public Nullable<int> Default_Credit_Card_Cd { get; set; }
        public bool Enable_Cash_Credit_On_Header { get; set; }
        public short Generate_voucher_no_method { get; set; }
        public bool Import_Cash_Credit_on_link { get; set; }
        public bool Overwrite_Price_On_Import { get; set; }
        public bool Show_In_Toolbar { get; set; }
        public bool Allow_duplicate_refrence_no { get; set; }
        public bool Show_Print_sr_no { get; set; }
        public int Ribbon_Icon_Id { get; set; }
        public bool Show_Pack_Qty { get; set; }
        public bool Setfocus_To_Qty_After_Name_Entered { get; set; }
        public bool Allow_Ldgr_Name_Alteration { get; set; }
        public bool show_proj_cd_on_header { get; set; }
        public bool show_activity_cd_on_header { get; set; }
        public bool Show_Activity_Task_In_Details { get; set; }
        public bool show_Non_Inventory_Item_Only { get; set; }
        public bool show_Activity_In_Detail { get; set; }
        public bool Show_Default_Qty_one { get; set; }
        public bool Show_Flex_1_In_Footer { get; set; }
        public bool Show_Item_Remark_In_List { get; set; }
        public bool Show_Flex_1_In_List { get; set; }
        public bool Enable_start_end_date { get; set; }
        public bool Enable_delivery_date { get; set; }
        public bool Enable_delivery_return_date { get; set; }
        public bool Check_Stock_Availability { get; set; }
        public bool Minimum_Rent_price_check { get; set; }
        public bool Show_Reporting_Unit_In_Status { get; set; }
        public bool Show_generate_barcode_button { get; set; }
        public bool show_hidden_discount { get; set; }
        public bool enable_customer_default_discount { get; set; }
        public bool Show_Package { get; set; }
        public bool Show_Supplier_Barcode { get; set; }
        public bool Show_Flex_2_In_Footer { get; set; }
        public bool Show_Flex_2_In_List { get; set; }
        public bool Show_Flex_3_In_Footer { get; set; }
        public bool Show_Flex_3_In_List { get; set; }
        public Nullable<int> default_credit_voucher_cd { get; set; }
        public bool Show_Link_No_In_Footer { get; set; }
        public bool Setfocus_To_Name_On_Newline { get; set; }
        public bool Show_Item_Cost_In_Status { get; set; }
        public bool Show_Production_Batch { get; set; }
        public bool Allow_Production_Batch_Add { get; set; }
        public bool Allow_Negative_Qty { get; set; }
        public bool Setfocus_To_Newline_After_Rate_Entered { get; set; }
        public bool Allow_Negative_Line_Discount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICS_Transaction> ICS_Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICS_Transaction> ICS_Transaction1 { get; set; }
        public virtual ICS_Transaction_Types ICS_Transaction_Types1 { get; set; }
        public virtual ICS_Transaction_Types ICS_Transaction_Types2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICS_Transaction_Types> ICS_Transaction_Types11 { get; set; }
        public virtual ICS_Transaction_Types ICS_Transaction_Types3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICS_Transaction_Types> ICS_Transaction_Types12 { get; set; }
        public virtual ICS_Transaction_Types ICS_Transaction_Types4 { get; set; }
        public virtual GL_Ledger GL_Ledger { get; set; }
    }
}
