//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntlmillReports.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IMILLEntities : DbContext
    {
        public IMILLEntities()
            : base("name=IMILLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ICS_Transaction> ICS_Transaction { get; set; }
        public virtual DbSet<ICS_Transaction_Details> ICS_Transaction_Details { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<SM_Location> SM_Location { get; set; }
        public virtual DbSet<SM_SALESMAN> SM_SALESMAN { get; set; }
        public virtual DbSet<ICS_Transaction_Types> ICS_Transaction_Types { get; set; }
        public virtual DbSet<GL_Ledger> GL_Ledger { get; set; }
    }
}
