//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntlmillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_SALESMAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SM_SALESMAN()
        {
            this.ICS_Transaction = new HashSet<ICS_Transaction>();
            this.GL_Ledger = new HashSet<GL_Ledger>();
        }
    
        public short Sman_Cd { get; set; }
        public short Supervisor_Cd { get; set; }
        public long Sman_No { get; set; }
        public string L_Sman_Name { get; set; }
        public string A_Sman_Name { get; set; }
        public string Addr_1 { get; set; }
        public string Addr_2 { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Civil_Id { get; set; }
        public string Passport_No { get; set; }
        public string Pf_No { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Comm_Percent { get; set; }
        public Nullable<decimal> Credit_Limit_Amount { get; set; }
        public Nullable<short> Credit_Limit_Days { get; set; }
        public bool Protected { get; set; }
        public bool Show { get; set; }
        public string Comments { get; set; }
        public short User_Cd { get; set; }
        public System.DateTime User_Date_Time { get; set; }
        public byte[] Time_Stamp { get; set; }
        public System.Guid row_id { get; set; }
        public int Default_locat_cd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICS_Transaction> ICS_Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_Ledger> GL_Ledger { get; set; }
    }
}
