//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int AddressId { get; set; }
        public string AddressName { get; set; }
        public string AddressNameAr { get; set; }
        public int PhoneNumber { get; set; }
        public string Block { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public int Floor { get; set; }
        public string Flat { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> Area_AreaId { get; set; }
        public Nullable<System.Guid> Customer_CustomerGuid { get; set; }
        public Nullable<int> Governorates_GovernorateId { get; set; }
        public string FullAddress { get; set; }
        public string PACINumber { get; set; }
        public string Avenue { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Governorate Governorate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
