//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDeposit
    {
        public int Oid { get; set; }
        public System.DateTime TransDate { get; set; }
        public decimal Salhiyah { get; set; }
        public decimal Salmiya { get; set; }
        public decimal Nuzha { get; set; }
        public decimal Dahiya { get; set; }
        public decimal Khaldiya { get; set; }
        public decimal Qortuba { get; set; }
        public decimal Kaifan { get; set; }
        public decimal Avenues { get; set; }
        public decimal KPC { get; set; }
        public decimal Yarmouk { get; set; }
        public decimal Zahara { get; set; }
        public decimal Mall360 { get; set; }
        public decimal Dasma { get; set; }
        public decimal Gate { get; set; }
        public decimal Shahuda { get; set; }
        public decimal Surra { get; set; }
        public decimal Bnied { get; set; }
        public decimal Jahra { get; set; }
        public decimal Kout { get; set; }
        public decimal Av4 { get; set; }
        public decimal Fintas { get; set; }
        public decimal Misc { get; set; }
        public decimal Misc2 { get; set; }
        public decimal Cash { get; set; }
        public string DepositBy { get; set; }
        public string Comments { get; set; }
        public decimal TotalCash { get; set; }
        public decimal Innova { get; set; }
        public decimal Hamra { get; set; }
    }
}
