//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDeposit
    {
        public int Oid { get; set; }
        public System.DateTime TransDate { get; set; }
        public decimal Salhiyah { get; set; }
        public decimal Salmiya { get; set; }
        public decimal Nuzha { get; set; }
        public decimal Dahiya { get; set; }
        public decimal Khaldiya { get; set; }
        public decimal Qortuba { get; set; }
        public decimal Kaifan { get; set; }
        public decimal Avenues { get; set; }
        public decimal KPC { get; set; }
        public decimal Yarmouk { get; set; }
        public decimal Zahara { get; set; }
        public decimal Mall360 { get; set; }
        public decimal Dasma { get; set; }
        public decimal Gate { get; set; }
        public decimal Shahuda { get; set; }
        public decimal Surra { get; set; }
        public decimal Bnied { get; set; }
        public decimal Jahra { get; set; }
        public decimal Kout { get; set; }
        public decimal Av4 { get; set; }
        public decimal Fintas { get; set; }
        public decimal Misc { get; set; }
        public decimal Misc2 { get; set; }
        public decimal Cash { get; set; }
        public string DepositBy { get; set; }
        public string Comments { get; set; }
        public decimal TotalCash { get; set; }
        public decimal Innova { get; set; }
        public decimal Hamra { get; set; }
        public Nullable<decimal> SalhiyahAm { get; set; }
        public Nullable<decimal> SalhiyahPm { get; set; }
        public Nullable<decimal> SalmiyaAm { get; set; }
        public Nullable<decimal> SalmiyaPm { get; set; }
        public Nullable<decimal> NuzhaAm { get; set; }
        public Nullable<decimal> NuzhaPm { get; set; }
        public Nullable<decimal> DahiyaAm { get; set; }
        public Nullable<decimal> DahiyaPm { get; set; }
        public Nullable<decimal> KhaldiyaAm { get; set; }
        public Nullable<decimal> KhaldiyaPm { get; set; }
        public Nullable<decimal> QortubaAm { get; set; }
        public Nullable<decimal> QortubaPm { get; set; }
        public Nullable<decimal> KaifanAm { get; set; }
        public Nullable<decimal> KaifanPm { get; set; }
        public Nullable<decimal> AvenuesAm { get; set; }
        public Nullable<decimal> AvenuesPm { get; set; }
        public Nullable<decimal> KPCAm { get; set; }
        public Nullable<decimal> KPCPm { get; set; }
        public Nullable<decimal> YarmoukAm { get; set; }
        public Nullable<decimal> YarmoukPm { get; set; }
        public Nullable<decimal> ZaharaAm { get; set; }
        public Nullable<decimal> ZaharaPm { get; set; }
        public Nullable<decimal> Mall360Am { get; set; }
        public Nullable<decimal> Mall360Pm { get; set; }
        public Nullable<decimal> DasmaAm { get; set; }
        public Nullable<decimal> DasmaPm { get; set; }
        public Nullable<decimal> GateAm { get; set; }
        public Nullable<decimal> GatePm { get; set; }
        public Nullable<decimal> ShahudaAm { get; set; }
        public Nullable<decimal> ShahudaPm { get; set; }
        public Nullable<decimal> SurraAm { get; set; }
        public Nullable<decimal> SurraPm { get; set; }
        public Nullable<decimal> HamraAm { get; set; }
        public Nullable<decimal> HamraPm { get; set; }
        public Nullable<decimal> BniedAm { get; set; }
        public Nullable<decimal> BniedPm { get; set; }
        public Nullable<decimal> JahraAm { get; set; }
        public Nullable<decimal> JahraPm { get; set; }
        public Nullable<decimal> KoutAm { get; set; }
        public Nullable<decimal> KoutPm { get; set; }
        public Nullable<decimal> Av4Am { get; set; }
        public Nullable<decimal> Av4Pm { get; set; }
        public Nullable<decimal> FintasAm { get; set; }
        public Nullable<decimal> FintasPm { get; set; }
    }
}
