//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchUser
    {
        public System.Guid BranchUserGuid { get; set; }
        public string UserId { get; set; }
        public string BranchUserName { get; set; }
        public string BranchUserNameAr { get; set; }
        public Nullable<int> ContactNumber { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> branch_BranchId { get; set; }
        public string Email { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
