//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICS_Item_Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ICS_Item_Group()
        {
            this.ICS_Item = new HashSet<ICS_Item>();
            this.ICS_Item_Group1 = new HashSet<ICS_Item_Group>();
        }
    
        public int Group_Cd { get; set; }
        public int M_Group_Cd { get; set; }
        public long Group_No { get; set; }
        public string L_Group_Name { get; set; }
        public string A_Group_Name { get; set; }
        public short Group_Level { get; set; }
        public bool Show { get; set; }
        public bool Protected { get; set; }
        public string Comments { get; set; }
        public short User_Cd { get; set; }
        public System.DateTime User_Date_Time { get; set; }
        public byte[] Time_Stamp { get; set; }
        public System.Guid row_id { get; set; }
        public string Parent_Groups { get; set; }
        public Nullable<int> Parent_Group_cd_1 { get; set; }
        public Nullable<int> Parent_Group_cd_2 { get; set; }
        public Nullable<int> Parent_Group_cd_3 { get; set; }
        public Nullable<int> Parent_Group_cd_4 { get; set; }
        public Nullable<int> Parent_Group_cd_5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICS_Item> ICS_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICS_Item_Group> ICS_Item_Group1 { get; set; }
        public virtual ICS_Item_Group ICS_Item_Group2 { get; set; }
    }
}
