//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICS_Transaction_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ICS_Transaction_Details()
        {
            this.ICS_Transaction_Details1 = new HashSet<ICS_Transaction_Details>();
        }
    
        public long Line_No { get; set; }
        public long Entry_Id { get; set; }
        public Nullable<short> Add_Locat_Cd { get; set; }
        public Nullable<short> Less_Locat_Cd { get; set; }
        public long Prod_Cd { get; set; }
        public Nullable<long> Project_Cd { get; set; }
        public long Unit_Entry_ID { get; set; }
        public Nullable<long> Linked_Line_No { get; set; }
        public decimal Exchange_Rate { get; set; }
        public string Prod_Name { get; set; }
        public string Reference_No { get; set; }
        public decimal Qty { get; set; }
        public decimal Base_Qty { get; set; }
        public decimal Processed_Qty { get; set; }
        public Nullable<decimal> Balance_Qty { get; set; }
        public decimal FC_Rate { get; set; }
        public decimal FC_Prod_Dis { get; set; }
        public decimal FC_Amount { get; set; }
        public Nullable<decimal> LC_Rate { get; set; }
        public Nullable<decimal> LC_Prod_Dis { get; set; }
        public Nullable<decimal> LC_Amount { get; set; }
        public decimal Prod_Exp_Amt { get; set; }
        public string Promo_Type { get; set; }
        public decimal Item_Cost { get; set; }
        public bool Dis_In_Percent { get; set; }
        public bool Linked { get; set; }
        public bool Show { get; set; }
        public long GL_Post_Sequence_Counter { get; set; }
        public byte Status { get; set; }
        public System.DateTime User_Date_Time { get; set; }
        public System.Guid row_id { get; set; }
        public decimal Non_Stock_Manual_Cost { get; set; }
        public byte Item_Type_Cd { get; set; }
        public bool Is_Dented { get; set; }
        public string Rate_UOM_Symbol { get; set; }
        public decimal Weight { get; set; }
        public Nullable<short> Linked_To_Voucher_Type { get; set; }
        public Nullable<long> Linked_To_Line_Id { get; set; }
        public decimal Processed_SQ_Base_Qty { get; set; }
        public decimal Processed_PO_Base_Qty { get; set; }
        public decimal Processed_GRN_Base_Qty { get; set; }
        public decimal Processed_CQ_Base_Qty { get; set; }
        public decimal Processed_SO_Base_Qty { get; set; }
        public decimal Processed_INV_Base_Qty { get; set; }
        public decimal Processed_CSR_Base_Qty { get; set; }
        public decimal Processed_SR_Base_Qty { get; set; }
        public decimal Processed_STS_Base_Qty { get; set; }
        public decimal Processed_ESTK_Base_Qty { get; set; }
        public decimal Processed_SSTK_Base_Qty { get; set; }
        public decimal Processed_Others_Base_Qty { get; set; }
        public Nullable<decimal> Balance_Qty_1 { get; set; }
        public string Pre_Text { get; set; }
        public string Post_Text { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public decimal Fc_Prod_Dis_Per { get; set; }
        public string Flex1 { get; set; }
        public decimal Commission_Amt { get; set; }
        public decimal master_discount { get; set; }
        public Nullable<int> Print_sr_no { get; set; }
        public Nullable<decimal> Pack_Qty { get; set; }
        public Nullable<decimal> Loose_Qty { get; set; }
        public string Barcode { get; set; }
        public Nullable<long> Acty_Task_Cd { get; set; }
        public Nullable<long> Acty_Cd { get; set; }
        public Nullable<decimal> Package { get; set; }
        public string batch_cd { get; set; }
        public Nullable<bool> production_status { get; set; }
        public string Additional_Field_1 { get; set; }
        public string Additional_Field_2 { get; set; }
        public string Additional_Field_3 { get; set; }
        public string Additional_Field_4 { get; set; }
        public string Additional_Field_5 { get; set; }
        public string Additional_Field_6 { get; set; }
        public string Additional_Field_7 { get; set; }
    
        public virtual ICS_Item ICS_Item { get; set; }
        public virtual ICS_Transaction ICS_Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICS_Transaction_Details> ICS_Transaction_Details1 { get; set; }
        public virtual ICS_Transaction_Details ICS_Transaction_Details2 { get; set; }
        public virtual SM_Location SM_Location { get; set; }
        public virtual SM_Location SM_Location1 { get; set; }
    }
}
