//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICS_Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ICS_Transaction()
        {
            this.ICS_Transaction_Details = new HashSet<ICS_Transaction_Details>();
            this.ICS_Transaction1 = new HashSet<ICS_Transaction>();
        }
    
        public long Entry_Id { get; set; }
        public short Voucher_Type { get; set; }
        public short Locat_Cd { get; set; }
        public Nullable<int> Ldgr_Cd { get; set; }
        public short Sman_Cd { get; set; }
        public Nullable<int> Cash_Cd { get; set; }
        public Nullable<short> Linked_To_Voucher_Type { get; set; }
        public Nullable<long> Linked_To_Entry_Id { get; set; }
        public Nullable<long> Batch_Cd { get; set; }
        public decimal Exchange_Rate { get; set; }
        public System.DateTime Voucher_Date { get; set; }
        public long Voucher_No { get; set; }
        public string Reference_No { get; set; }
        public bool Is_Cash { get; set; }
        public decimal Voucher_Amt_FC { get; set; }
        public Nullable<decimal> Voucher_Amt_LC { get; set; }
        public decimal Discount_Amt_FC { get; set; }
        public Nullable<decimal> Discount_Amt_LC { get; set; }
        public Nullable<decimal> Net_Amt_FC { get; set; }
        public Nullable<decimal> Net_Amt_LC { get; set; }
        public decimal Expenses_Amt { get; set; }
        public decimal Paid_Amt { get; set; }
        public decimal Due_Amt { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public bool On_Hand_Stock_Affected { get; set; }
        public bool Close_Transaction { get; set; }
        public bool Transaction_Processed { get; set; }
        public bool Transaction_Year_Closed { get; set; }
        public int Printed_Counter { get; set; }
        public bool Processed { get; set; }
        public bool Reversed { get; set; }
        public bool Reconciled { get; set; }
        public Nullable<System.DateTime> Reconciled_Date { get; set; }
        public string Comments { get; set; }
        public bool Posted_Invnt { get; set; }
        public byte Status { get; set; }
        public bool Posted_GL_Party { get; set; }
        public bool Posted_GL_Expense { get; set; }
        public bool Posted_GL_Inventory { get; set; }
        public bool Posted_GL { get; set; }
        public short User_Cd { get; set; }
        public System.DateTime User_Date_Time { get; set; }
        public byte[] Time_Stamp { get; set; }
        public System.Guid row_id { get; set; }
        public string Anly_Code_1 { get; set; }
        public string Anly_Code_2 { get; set; }
        public Nullable<byte> Anly_Head_No_1 { get; set; }
        public Nullable<byte> Anly_Head_No_2 { get; set; }
        public Nullable<short> Curr_Cd { get; set; }
        public int Revision_No { get; set; }
        public decimal Cash_Amt_FC { get; set; }
        public Nullable<int> Credit_Card_Ldgr_Cd { get; set; }
        public decimal Credit_Card_Amt_FC { get; set; }
        public decimal Change_Amt_FC { get; set; }
        public decimal Amount_Received { get; set; }
        public Nullable<int> POS_Counter_Cd { get; set; }
        public Nullable<int> Expenses_Ldgr_Cd { get; set; }
        public Nullable<int> Consignment_Cd { get; set; }
        public decimal Discount_Percent { get; set; }
        public string Ldgr_Name { get; set; }
        public Nullable<long> Project_Cd { get; set; }
        public Nullable<long> Acty_Cd { get; set; }
        public Nullable<System.DateTime> From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public Nullable<System.DateTime> Delevery_Date { get; set; }
        public Nullable<System.DateTime> Return_Date { get; set; }
        public Nullable<decimal> Discount2_percent { get; set; }
        public Nullable<decimal> Discount2_Amt { get; set; }
        public string Credit_voucher_no { get; set; }
        public Nullable<decimal> Credit_voucher_Amt_FC { get; set; }
        public Nullable<int> Credit_Voucher_Ldgr_Cd { get; set; }
        public string Credit_Card_Type { get; set; }
        public string Additional_Field_1 { get; set; }
        public string Additional_Field_2 { get; set; }
        public string Additional_Field_3 { get; set; }
        public string Additional_Field_4 { get; set; }
        public string Additional_Field_5 { get; set; }
        public string Additional_Field_6 { get; set; }
        public string Additional_Field_7 { get; set; }
    
        public virtual GL_Ledger GL_Ledger { get; set; }
        public virtual GL_Ledger GL_Ledger1 { get; set; }
        public virtual GL_Ledger GL_Ledger2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICS_Transaction_Details> ICS_Transaction_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICS_Transaction> ICS_Transaction1 { get; set; }
        public virtual ICS_Transaction ICS_Transaction2 { get; set; }
        public virtual ICS_Transaction_Types ICS_Transaction_Types { get; set; }
        public virtual ICS_Transaction_Types ICS_Transaction_Types1 { get; set; }
        public virtual SM_Location SM_Location { get; set; }
        public virtual SM_SALESMAN SM_SALESMAN { get; set; }
    }
}
