//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICS_Unit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ICS_Unit()
        {
            this.ICS_Item = new HashSet<ICS_Item>();
            this.ICS_Item_Unit_Details = new HashSet<ICS_Item_Unit_Details>();
            this.ICS_Item_Unit_Details1 = new HashSet<ICS_Item_Unit_Details>();
        }
    
        public short Unit_Cd { get; set; }
        public long Unit_No { get; set; }
        public string L_Unit_Name { get; set; }
        public string A_Unit_Name { get; set; }
        public string Symbol { get; set; }
        public byte Decimals { get; set; }
        public bool Protected { get; set; }
        public short User_Cd { get; set; }
        public System.DateTime User_Date_Time { get; set; }
        public byte[] Time_Stamp { get; set; }
        public System.Guid row_id { get; set; }
        public string A_Symbol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICS_Item> ICS_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICS_Item_Unit_Details> ICS_Item_Unit_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICS_Item_Unit_Details> ICS_Item_Unit_Details1 { get; set; }
    }
}
