//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ImillReportsEntities : DbContext
    {
        public ImillReportsEntities()
            : base("name=ImillReportsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Transaction_2020> Transaction_2020 { get; set; }
        public virtual DbSet<Trans_Detail_2020> Trans_Detail_2020 { get; set; }
        public virtual DbSet<Trans_Detail_2019> Trans_Detail_2019 { get; set; }
        public virtual DbSet<Transaction_2019> Transaction_2019 { get; set; }
    }
}
