//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ImillReportsEntities : DbContext
    {
        public ImillReportsEntities()
            : base("name=ImillReportsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Transaction_2020> Transaction_2020 { get; set; }
        public virtual DbSet<Trans_Detail_2020> Trans_Detail_2020 { get; set; }
        public virtual DbSet<Trans_Detail_2019> Trans_Detail_2019 { get; set; }
        public virtual DbSet<Transaction_2019> Transaction_2019 { get; set; }
        public virtual DbSet<Trans_Detail_2021> Trans_Detail_2021 { get; set; }
        public virtual DbSet<Transaction_2021> Transaction_2021 { get; set; }
        public virtual DbSet<ReportEmailTransaction> ReportEmailTransactions { get; set; }
        public virtual DbSet<ReportEmailMap> ReportEmailMaps { get; set; }
        public virtual DbSet<Trans_Detail_2018> Trans_Detail_2018 { get; set; }
        public virtual DbSet<Transaction_2018> Transaction_2018 { get; set; }
        public virtual DbSet<Trans_Detail_2015> Trans_Detail_2015 { get; set; }
        public virtual DbSet<Trans_Detail_2016> Trans_Detail_2016 { get; set; }
        public virtual DbSet<Trans_Detail_2017> Trans_Detail_2017 { get; set; }
        public virtual DbSet<Transaction_2015> Transaction_2015 { get; set; }
        public virtual DbSet<Transaction_2016> Transaction_2016 { get; set; }
        public virtual DbSet<Transaction_2017> Transaction_2017 { get; set; }
        public virtual DbSet<BankDeposit> BankDeposits { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
    }
}
