//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class intlmill_cash_register
    {
        public int id { get; set; }
        public System.DateTime trans_date_time { get; set; }
        public string location { get; set; }
        public string salesman { get; set; }
        public string shift_type { get; set; }
        public int shift_count { get; set; }
        public Nullable<decimal> cheque { get; set; }
        public Nullable<decimal> other { get; set; }
        public Nullable<decimal> carriage { get; set; }
        public Nullable<decimal> online { get; set; }
        public Nullable<decimal> knet { get; set; }
        public Nullable<decimal> visa { get; set; }
        public Nullable<decimal> reserve { get; set; }
        public Nullable<decimal> expense { get; set; }
        public decimal total_cash { get; set; }
        public decimal net_cash { get; set; }
        public Nullable<int> d_20000 { get; set; }
        public Nullable<int> d_10000 { get; set; }
        public Nullable<int> d_5000 { get; set; }
        public Nullable<int> d_1000 { get; set; }
        public Nullable<int> d_0500 { get; set; }
        public Nullable<int> d_0250 { get; set; }
        public Nullable<int> d_0100 { get; set; }
        public Nullable<int> d_0050 { get; set; }
        public Nullable<int> d_0020 { get; set; }
        public Nullable<int> d_0010 { get; set; }
        public Nullable<int> d_0005 { get; set; }
        public decimal total_sales { get; set; }
        public decimal net_sales { get; set; }
        public string staff_date { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<System.DateTime> ActualStaffDate { get; set; }
        public Nullable<short> Sman_Cd { get; set; }
        public Nullable<short> Locat_Cd { get; set; }
        public Nullable<int> CrOid { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
