//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int OrderItemId { get; set; }
        public int Quantity { get; set; }
        public decimal Subtotal { get; set; }
        public Nullable<int> Order_OrderId { get; set; }
        public Nullable<int> ProductAttributeValue_ProductAttributeValueId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ProductAttributeValue ProductAttributeValue { get; set; }
    }
}
