//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.Shipments = new HashSet<Shipment>();
        }
    
        public int OrderId { get; set; }
        public int CustomOrderNumber { get; set; }
        public string CustomerIpAddress { get; set; }
        public string OrderNotes { get; set; }
        public int OrderStatus { get; set; }
        public Nullable<System.DateTime> PaidDateUtc { get; set; }
        public int PaymentStatus { get; set; }
        public int PaymentType { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> Address_AddressId { get; set; }
        public Nullable<System.Guid> Customer_CustomerGuid { get; set; }
        public Nullable<int> Branch_BranchId { get; set; }
        public decimal TotalOrderAmount { get; set; }
        public decimal ShippingCharge { get; set; }
        public Nullable<int> Delivery_Oid { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public Nullable<int> DeliveryMode_Oid { get; set; }
        public Nullable<int> TimeSlot_Oid { get; set; }
        public string reference_number { get; set; }
        public string result { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual DeliveryMode DeliveryMode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipment> Shipments { get; set; }
    }
}
