//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosOrder
    {
        public int Oid { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string OrderId { get; set; }
        public string ClientName { get; set; }
        public string MobileNo { get; set; }
        public System.DateTime DeliveryOn { get; set; }
        public string Address { get; set; }
        public decimal TotalOrderValue { get; set; }
        public decimal ShippingFees { get; set; }
        public decimal NetAmount { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentStatus { get; set; }
        public string Driver { get; set; }
        public short Locat_Cd { get; set; }
        public bool IsPrinted { get; set; }
        public bool AllowSync { get; set; }
    }
}
