//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public long Oid { get; set; }
        public long EntryId { get; set; }
        public int LdgrCd { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public int LpoStatus { get; set; }
        public int LpoInvoiceStatus { get; set; }
        public int LpoPaymentStatus { get; set; }
        public string PaymentRemarks { get; set; }
        public string GmComments { get; set; }
        public Nullable<System.DateTime> LpoStatusTransDate { get; set; }
        public Nullable<System.DateTime> LpoPaymentTransDate { get; set; }
        public Nullable<int> QAStatus { get; set; }
        public string QARemarks { get; set; }
        public Nullable<System.DateTime> QAStatusTransDate { get; set; }
    }
}
