//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportEmailTransaction
    {
        public int Oid { get; set; }
        public System.DateTime ReportDate { get; set; }
        public bool IsWeekly { get; set; }
        public bool IsMonthly { get; set; }
        public bool IsYearly { get; set; }
        public int ReportEmailMap { get; set; }
    }
}
