//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportEmailMap
    {
        public int Oid { get; set; }
        public string Email { get; set; }
        public bool IsRegForEmail { get; set; }
        public bool IsMon { get; set; }
        public bool IsTues { get; set; }
        public bool IsWed { get; set; }
        public bool IsThurs { get; set; }
        public bool IsFri { get; set; }
        public bool IsSat { get; set; }
        public bool IsSun { get; set; }
        public Nullable<System.TimeSpan> WeeklyTime { get; set; }
    }
}
