//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Oid { get; set; }
        public System.DateTime SerialDate { get; set; }
        public long SerialNumber { get; set; }
        public Nullable<int> BackDays { get; set; }
        public Nullable<System.DateTime> RptEmailDate { get; set; }
        public Nullable<bool> WeekRptEmailSent { get; set; }
    }
}
