//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FCCCentralizedDBEntities1 : DbContext
    {
        public FCCCentralizedDBEntities1()
            : base("name=FCCCentralizedDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_EmpAttendance> tbl_EmpAttendance { get; set; }
        public virtual DbSet<tbl_EmpLocShiftMap> tbl_EmpLocShiftMap { get; set; }
        public virtual DbSet<tbl_Employees> tbl_Employees { get; set; }
        public virtual DbSet<tbl_Location> tbl_Location { get; set; }
        public virtual DbSet<tbl_Shift> tbl_Shift { get; set; }
        public virtual DbSet<tbl_Transactions> tbl_Transactions { get; set; }
        public virtual DbSet<tbl_EmployeeLeaves> tbl_EmployeeLeaves { get; set; }
        public virtual DbSet<tbl_ShiftEmailSettings> tbl_ShiftEmailSettings { get; set; }
        public virtual DbSet<tbl_ShiftEmailMap> tbl_ShiftEmailMap { get; set; }
        public virtual DbSet<tbl_Device> tbl_Device { get; set; }
        public virtual DbSet<tbl_EmpTransaction> tbl_EmpTransaction { get; set; }
    }
}
