//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Transactions
    {
        public int Oid { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime TransDate { get; set; }
        public string DeviceCode { get; set; }
        public string Employee { get; set; }
        public string LocationName { get; set; }
        public int LocationOid { get; set; }
        public string TemperatureIn { get; set; }
        public string TemperatureOut { get; set; }
        public System.DateTime PunchIn { get; set; }
        public System.DateTime PunchOut { get; set; }
        public System.TimeSpan LateIn { get; set; }
        public System.TimeSpan EarlyOut { get; set; }
        public Nullable<decimal> TotalHoursWorked { get; set; }
        public Nullable<System.TimeSpan> ShiftStart { get; set; }
        public Nullable<System.TimeSpan> ShiftEnd { get; set; }
        public bool IsOpened { get; set; }
        public string EmployeeAr { get; set; }
    }
}
