//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmpLocShiftMap
    {
        public int Oid { get; set; }
        public int EmpId { get; set; }
        public int LocationOid { get; set; }
        public int ShiftOid { get; set; }
        public Nullable<System.DateTime> fromDate { get; set; }
        public Nullable<System.DateTime> toDate { get; set; }
        public Nullable<bool> IsMon { get; set; }
        public Nullable<bool> IsTues { get; set; }
        public Nullable<bool> IsWed { get; set; }
        public Nullable<bool> IsThur { get; set; }
        public Nullable<bool> IsFri { get; set; }
        public Nullable<bool> IsSat { get; set; }
        public Nullable<bool> IsSun { get; set; }
    
        public virtual tbl_Employees tbl_Employees { get; set; }
        public virtual tbl_Location tbl_Location { get; set; }
        public virtual tbl_Shift tbl_Shift { get; set; }
    }
}
