//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ShiftEmailMap
    {
        public int Oid { get; set; }
        public int ShiftOid { get; set; }
        public bool IsEmailSent { get; set; }
        public System.DateTime TransDate { get; set; }
        public bool IsForStart { get; set; }
        public int ShiftEmailSettingOid { get; set; }
    }
}
