//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Device
    {
        public int DeviceID { get; set; }
        public string DeviceCode { get; set; }
        public string DeviceIP { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public string Companycode { get; set; }
        public string Divisioncode { get; set; }
        public string Areacode { get; set; }
        public string Departmentcode { get; set; }
    }
}
