//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ShiftEmailSettings
    {
        public int Oid { get; set; }
        public string Email { get; set; }
        public bool IsRegForEmail { get; set; }
        public string RegisterForShifts { get; set; }
        public System.TimeSpan EmailStartRange { get; set; }
        public System.TimeSpan EmailEndRange { get; set; }
        public System.TimeSpan LateInRange { get; set; }
        public System.TimeSpan EarlyOutRange { get; set; }
    }
}
