//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmpAttendance
    {
        public long ID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<System.DateTime> Login { get; set; }
        public Nullable<System.DateTime> Logout { get; set; }
        public string EmployeeName { get; set; }
        public string CardID { get; set; }
        public string DeviceCode { get; set; }
        public string Status { get; set; }
    }
}
