//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Location()
        {
            this.tbl_EmpLocShiftMap = new HashSet<tbl_EmpLocShiftMap>();
        }
    
        public int Oid { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public Nullable<short> Locat_Cd { get; set; }
        public string DeviceCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EmpLocShiftMap> tbl_EmpLocShiftMap { get; set; }
    }
}
