//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmpTransaction
    {
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> TransactionYear { get; set; }
        public Nullable<int> TransactionMonth { get; set; }
        public Nullable<int> TransactionDate { get; set; }
        public Nullable<int> TransactionHour { get; set; }
        public Nullable<int> TransactionMinute { get; set; }
        public Nullable<int> TransactionSecond { get; set; }
        public string TransactionType { get; set; }
        public string DeviceCode { get; set; }
        public long Timestamp { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<bool> pushed { get; set; }
        public Nullable<System.DateTime> TransactionDateTime { get; set; }
        public string CardID { get; set; }
        public Nullable<long> Maskflag { get; set; }
        public Nullable<long> Permission { get; set; }
    }
}
