//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImillReports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishList
    {
        public int Oid { get; set; }
        public long EntryId { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public long Prod_Cd { get; set; }
        public decimal RequestedQty { get; set; }
        public decimal RemainingQty { get; set; }
        public long TransactionOid { get; set; }
        public long TransDetailOid { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public Nullable<long> Locat_Cd { get; set; }
    }
}
